import { Button, Input } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HoaToc from '../images/img/icon-hoa-toc.png'
import Fullfill from '../images/3pl_fullfillment.png'
import Quocte from '../images/quoc_te.png'
import Banner from '../images/img/banner.png'

export default function Home() {
  return (
    <>
      <div className='w-100 position-relative slide-v2'>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div id='carouselExampleIndicators_pc' className='carousel slide d-none d-md-block' data-ride='carousel'>
          <ol className='carousel-indicators'>

          </ol>
          <div className='carousel-inner'>
            <div className='carousel-item active'>
              <a target="_blank">
                <Image
                  alt="Next.js logo"
                  className='w-100'
                  src="https://cdn.ntlogistics.vn/uploads/banners/2021/12/11/banner_christmas_web.jpg"
                  width={1425}
                  height={504}
                />
              </a>
            </div>
          </div>
        </div>
        <div id="carouselExampleIndicators_mb" className="carousel slide d-block d-md-none" data-ride='carousel'>
          <div className="carousel-inner d-block d-md-none">
            <div className="carousel-item active">
              <Image
                alt="Next.js logo"
                className='w-100'
                src="https://cdn.ntlogistics.vn/uploads/banners/2020/12/31/banner_mb_ntl.jpg"
                width={1425}
                height={504}
              />
            </div>
          </div>
        </div>
        <div className="col-lg-6 col-md-12 col-sm-12 col-12 offset-lg-3 wp-slide flex-container center mt-lg-5 pt-lg-5" style={{ height: 'auto' }}>
          <div className="mt-md-n5 mt-n3 more-than-log">

            Hơn cả một dịch vụ

          </div>
          <div className="d-flex justify-content-center align-items-center ml-md-n2 mr-md-n2 ml-n1 mr-n1">
            <div className="ml-0 mr-n1">
              <span className="mx-auto d-block top-slide" />
              <div className="box-cube">
                <a href="tra-cuoc.html">
                  <span className="icon-slide font-size-30 ntl-Document-2">
                    <span className="path1"></span><span id="ntl-Document-2" className="path2"></span><span className="path3"></span><span className="path4"></span><span className="path5"></span><span className="path6"></span><span className="path7"></span><span className="path8"></span><span className="path9"></span><span className="path10"></span><span className="path11"></span><span className="path12"></span><span className="path13"></span><span className="path14"></span></span>
                  <p className="mt-1 mt-sm-2 mb-1 mb-sm-3 font-size-14">Tạo vận đơn</p>
                  <span className="d-block line"></span>
                </a>
              </div>

            </div>
            <div className="mx-0" style={{ zIndex: 2 }}>
              <span className="mx-auto d-block top-slide"></span>
              <div className="box-cube active-box-cube">
                <a href="tra-van-don.html">
                  <span className="icon-slide font-size-30 ntl-Box-1"><span id="ntl-Box-1" className="path1"></span><span className="path2"></span><span className="path3"></span><span className="path4"></span><span className="path5"></span></span>
                  <p className="mt-2 font-size-14">Tra cứu vận đơn</p>
                  <span className="d-block line"></span>
                </a>
              </div>
            </div>
            <div className="mr-0 ml-n1">
              <span className="mx-auto d-block top-slide"></span>
              <div className="box-cube">
                <a className="danh-sach-buu-cuc.html">
                  <span className="icon-slide font-size-30 ntl-Location-2"><span id="ntl-Location-2" className="path1"></span><span id="ntl-Location-22" className="path2"></span><span className="path3"></span><span className="path4"></span><span className="path5"></span></span>
                  <p className="mt-1 mt-sm-2 mb-1 mb-sm-3 font-size-14">Danh sách bưu cục</p>
                  <span className="d-block line"></span>
                </a>
              </div>
            </div>
          </div>
          <div className="w-100 d-inline-block pl-1 pr-1">
            <form className="row position-relative search mt-1 mt-md-3" action="tra-van-don.html" method="get"  id="tracking_top">
              <div className="col-lg-10 col-sm-10 col-9 pr-0 pr-sm-2" style={{ backgroundColor: 'white' }}>
                <Input placeholder='Nhập mã vận đơn' size='sm' id="bill" className="form-control rounded-0 border-0 tukhoa" />
                {/* <Input type="text" name="bill" id="bill" value="" placeholder="Nhập mã vận đơn" className="form-control rounded-0 border-0 tukhoa" autocomplete="off"> */}
              </div>
              <div className="col-lg-2 col-sm-2 col-3 pl-0">
                <Button className="btn w-100  rounded-0 pl-1 pr-1 btn-search-home" colorScheme='teal' size='md'>
                  Tra cứu
                </Button>
                {/* <button className="btn w-100  rounded-0 pl-1 pr-1 btn-search-home">Tra cứu</button> */}
              </div>
              {/* <span className="error col-lg-12" id="error_bill" className="display:none">Nhập mã vận đơn</span> */}
            </form>
          </div>
        </div>
      </div>


      {/* service */}

      <div className="w-100 wp-service ">
        <div className='container container-service'>
          <div className="row m-0">
            <a href="/tin-tuc/chuyen-phat-hoa-toc/" className="item-service  bg-fff translate text-center position-relative p-3">
              <p className="mb-3 mb-sm-0" style={{ height: 50 }} >
                <Image
                  alt="Next.js logo"
                  className='w-100'
                  src={HoaToc}
                  width={55}
                  height={55}
                />
                {/* <img src="images/img/icon-hoa-toc.png" alt="" className="icon-hoa-toc"> */}
              </p>
              Chuyển phát hỏa tốc
            </a>
            <a href="/tin-tuc/chuyen-phat-nhanh/" className="item-service  bg-fff translate text-center position-relative p-3">
              <p className="ntl-CPN1 mb-3 mb-sm-0"><span className="path1"></span><span className="path2"></span><span className="path3"></span><span className="path4"></span><span className="path5"></span><span className="path6"></span><span className="path7"></span><span className="path8"></span><span className="path9"></span><span className="path10"></span></p>
              Chuyển phát nhanh
            </a>
            <a href="/tin-tuc/dich-vu-chuyen-phat-ket-hop-mes/" className="item-service   bg-fff translate text-center position-relative p-3">
              <p className="ntl-CP-Ket-Hop mb-3 mb-sm-0"><span className="path1"></span><span className="path2"></span><span className="path3"></span><span className="path4"></span><span className="path5"></span><span className="path6"></span><span className="path7"></span><span className="path8"></span><span className="path9"></span><span className="path10"></span><span className="path11"></span><span className="path12"></span></p>
              Chuyển phát tiết kiệm
            </a>
            <a href="/tin-tuc/dich-vu-chuyen-phat-nhanh-duong-bo/" className="item-service   bg-fff translate text-center position-relative p-3">
              <p className="ntl-CP-duong-bo mb-3 mb-sm-0"><span className="path1"></span><span className="path2"></span><span className="path3"></span><span className="path4"></span><span className="path5"></span><span className="path6"></span><span className="path7"></span><span className="path8"></span><span className="path9"></span><span className="path10"></span><span className="path11"></span><span className="path12"></span><span className="path13"></span><span className="path14"></span><span className="path15"></span><span className="path16"></span><span className="path17"></span><span className="path18"></span><span className="path19"></span><span className="path20"></span><span className="path21"></span><span className="path22"></span><span className="path23"></span><span className="path24"></span><span className="path25"></span><span className="path26"></span><span className="path27"></span><span className="path28"></span><span className="path29"></span></p>
              Chuyển phát đường bộ
            </a>
            <a href="/tin-tuc/dv-van-chuyen-thuong-mai-dien-tu-cod/" className="item-service   bg-fff translate text-center position-relative p-3">
              <p className="ntl-Thu-ho-COD mb-3 mb-sm-0"><span className="path1"></span><span className="path2"></span><span className="path3"></span><span className="path4"></span><span className="path5"></span></p>
              Chuyển phát thu hộ (COD)
            </a>
            <a href="/tin-tuc/dich-vu-van-chuyen-nguyen-chuyen-xe/" className="item-service   bg-fff translate text-center position-relative p-3">
              <p className="ntl-Nguyen-xe mb-3 mb-sm-0"><span className="path1"></span><span className="path2"></span><span className="path3"></span></p>Thuê xe nguyên chuyến
            </a>
            <a href="/tin-tuc/chuyen-phat-quoc-te/" className="item-service   bg-fff translate text-center position-relative p-3">
              <p className="mb-3 mb-sm-0" style={{ height: 50 }} >
                <Image
                  alt="Next.js logo"
                  className='w-100'
                  src={Quocte}
                  width={55}
                  height={55}
                />
                {/* <img src="images/quoc_te.png" alt="" className="icon-hoa-toc"> */}
              </p>
              Chuyển phát Quốc Tế
            </a>
            <a href="/tin-tuc/3pl-fulfillment/" className="item-service   bg-fff translate text-center position-relative p-3">
              <p className="mb-3 mb-sm-0" style={{ height: 50 }}>
                <Image
                  alt="Next.js logo"
                  className='w-100'
                  src={Fullfill}
                  width={55}
                  height={55}
                />
                {/* <img src="images/3pl_fullfillment.png" alt="" className="icon-hoa-toc"> */}
              </p>
              3PL &amp; FulFillment
            </a>
          </div>
          <div className="w-100 text-center mt-3 text-service" style={{ display: 'block' }}>
            <div className="mb-2 mb-sm-0"><span className="ntl-Thin-Arrow-3 font-size-Thin-Arrow-3 mb-2"></span></div>
            <div className="pl-5 pl-sm-0 pr-5 pr-sm-0 ml-4 ml-sm-5 mr-4 mr-sm-0 font-size-18"><b className="SanFranciscoDisplay-Bold">Lựa chọn dịch vụ </b> bạn quan tâm</div>
          </div>
        </div>
      </div>
      <div className="w-100 text-center pt-4 pb-4 pt-sm-0 pb-sm-0">
        <a href="#" title="">
          <Image
            alt="Next.js logo"
            className='img-fluid'
            src={Banner}
            width={1425}
            height={284}
          />
        </a>
      </div>
      <div id='why' className='w-100 wp-about position-relative'>
        <div className="container">
          <div className="row align-items-center d-flex">
            <div className="col-lg-6 col-sm-12 col-12 left-about text-white text-center pt-3 pb-3 pr-md-5">
              <h1 className="text-service SanFranciscoDisplay-Bold pr-md-5">Tại sao lựa chọn dịch vụ tại <span className="text-FCD804">Nhất Tín Logistics?</span></h1>
              <p className="summary mt-2 mb-5 pr-md-5">
                Nhất Tín Logistics mang đến các dịch vụ Chuyển Phát Nhanh Vận Tải<br />
                trải dài khắp 63 tỉnh thành, đáp ứng mọi nhu cầu vận chuyển nhanh chóng thư từ,<br />
                hàng hóa của các quý khách hàng, đảm bảo chất lượng  cung cách phục vụ<br />
                Nhiệt Tình - Thân Thiện.
              </p>


              <div className="row pr-md-08">

                <div className="col-lg-4 col-sm-4 col-12 item-about">
                  <span className="ntl-COD-24h font-size-96"><span className="path1"></span><span className="path2"></span><span className="path3"></span><span className="path4"></span><span className="path5"></span></span>
                  <h5 className="title-h5 mt-3 mt-md-3 mb-4 mb-md-0 px-3">Hoàn tiền COD chỉ trong 24h</h5>
                </div>
                <div className="col-lg-4 col-sm-4 col-12 item-about">
                  <span className="ntl-Money font-size-96"><span className="path1"></span><span className="path2"></span><span className="path3"></span><span className="path4"></span><span className="path5"></span></span>
                  <h5 className="title-h5 mt-3 mt-md-3 mb-4 mb-md-0 px-2">Miễn cước thu hộ lên đến 5 triệu đồng</h5>
                </div>
                <div className="col-lg-4 col-sm-4 col-12 item-about">
                  <span className="ntl-Location-White1  font-size-96"><span className="path1"></span><span className="path2"></span><span className="path3"></span><span className="path4"></span></span>
                  <h5 className="title-h5 mt-3 mt-md-3 mb-4 mb-md-0 pl-1 pr-1">Mạng lưới phủ sóng 63 tỉnh thành</h5>
                </div>
              </div>

              <div className="row sendnowbox pt-0 pt-sm-4 pb-2 pb-sm-0">
                <a className="sendnow" href="tra-cuoc.html">Gửi hàng ngay<span className="ntl-Black-Arrow-4 icon-Arrow-4"></span></a>
              </div>
            </div>
            <div className="col-lg-6 col-sm-12 col-12 right-about pt-3 pb-3 pl-md-3">
              <ul>
                <li className="d-flex justify-content-md-start align-items-center ml-md-5 " style={{ marginTop: 20, paddingBottom: 15 }}>
                  <div className="mr-3 float-left"><span className="icon bg-white rounded-circle text-center ntl-Shipping-Car p-2 "></span></div>
                  <div className="float-left">
                    <div className="title-about SanFranciscoDisplay-Bold">Giao hàng hỏa tốc</div>
                    <span>Vận chuyển hàng nội thành siêu nhanh chỉ trong 3 tiếng<br />
                      Gửi liên tỉnh nhận liền ngay sau 12 - 24 tiếng</span>
                  </div>
                </li>
                <li className="d-flex jjustify-content-md-start align-items-center ml-md-5 " style={{ paddingBottom: 15 }} >
                  <div className="mr-3 float-left"><span className="icon bg-white rounded-circle text-center ntl-Box-time p-2 "></span></div>
                  <div className="float-left">
                    <div className="title-about SanFranciscoDisplay-Bold">Kiểm soát thời gian thực</div>
                    <span>Khách hàng luôn biết thực tế gói hàng của mình ở đâu,<br />
                      ai đang vận chuyển và ước tính thời gian được giao đến</span>
                  </div>
                </li>
                <li className="d-flex justify-content-md-start align-items-center ml-md-5 " style={{ paddingBottom: 15 }}>
                  <div className="mr-3 float-left"><span className="icon bg-white rounded-circle text-center ntl-Cart p-2 "></span></div>
                  <div className="float-left">
                    <div className="title-about SanFranciscoDisplay-Bold">Cơ sở vật chất hiện đại</div>
                    <span>Hệ thống kho bãi rộng rãi, xe tải 100% đóng thùng kín<br />
                      Trên 350 bưu cục và điểm giao nhận phủ sóng toàn quốc</span>
                  </div>
                </li>
                <li className="d-flex justify-content-md-start align-items-center ml-md-5 " style={{ paddingBottom: 15 }}>
                  <div className="mr-3 float-left"><span className="icon bg-white rounded-circle text-center ntl-Shield p-2 "></span></div>
                  <div className="float-left">
                    <div className="title-about SanFranciscoDisplay-Bold">Đảm bảo an toàn</div>
                    <span>Hàng hóa của khách hàng sẽ luôn được đảm bảo kỹ lưỡng và an toàn với các dịch vụ chuyển phát tại Nhất Tín</span>
                  </div>
                </li>
                <li className="d-flex justify-content-md-start align-items-center ml-md-5 " style={{ paddingBottom: 15 }}>
                  <div className="mr-3 float-left"><span className="icon bg-white rounded-circle text-center ntl-Head-phone p-2"></span>
                  </div>
                  <div className="float-left">
                    <div className="title-about SanFranciscoDisplay-Bold">Hỗ trợ trực tuyến</div>
                    <span className="unset-color">
                      Thời gian làm việc từ 7h đến 22h hàng ngày<br />
                      Phục vụ và giải đáp mọi thắc mắc của khách hàng<br />
                      Hotline: <a href="tel:1900636688">1900 63 6688</a><br />
                      Fanpage: <a href="https://www.facebook.com/nhattinlogistics" target="_blank">Fb.com/nhattinlogistics</a>
                    </span>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div className="w-100 coutdown" id="coutdown">
        <div className="container">
          <div className="row d-flex align-items-center text-center">
            <div className="col-lg2 pb-3 pt-5 pb-sm-5">
              <div className="icon"><span className="ntl-Buu-cuc"><span className="path1"></span><span className="path2"></span><span className="path3"></span><span className="path4"></span><span className="path5"></span><span className="path6"></span><span className="path7"></span><span className="path8"></span><span className="path9"></span><span className="path10"></span><span className="path11"></span><span className="path12"></span><span className="path13"></span><span className="path14"></span></span></div>
              <div className="count-tk">
                <span className="timer counter-number appear" data-to="350" data-speed="7000">350</span>
                <br /><span className="SanFranciscoDisplay-Bold">Bưu cục</span>
              </div>
            </div>
            <div className="col-lg2 pt-3 pb-3 pt-sm-5 pb-sm-5">
              <div className="icon"><span className="ntl-Nguyen-xe"><span className="path1"></span><span className="path2"></span><span className="path3"></span></span></div>
              <div className="count-tk">
                <span className="timer counter-number appear" data-to="400" data-speed="7000">400</span>
                <br /><span className="SanFranciscoDisplay-Bold">Xe</span>
              </div>
            </div>
            <div className="col-lg2 pt-3 pb-3 pt-sm-5 pb-sm-5">
              <div className="icon"><span className="ntl-Doi-tac"><span className="path1"></span><span className="path2"></span><span className="path3"></span><span className="path4"></span></span></div>
              <div className="count-tk">
                <span className="timer counter-number appear" data-to="36000" data-speed="7000">36.000</span>
                <br /><span className="SanFranciscoDisplay-Bold">Đối tác, Khách hàng</span>
              </div>
            </div>
            <div className="col-lg2 pt-3 pt-sm-5 pb-5">
              <div className="icon"><span className="ntl-NV"><span className="path1"></span><span className="path2"></span><span className="path3"></span><span className="path4"></span><span className="path5"></span><span className="path6"></span><span className="path7"></span><span className="path8"></span><span className="path9"></span><span className="path10"></span><span className="path11"></span><span className="path12"></span></span></div>
              <div className="count-tk">
                <span className="timer counter-number appear" data-to="3000" data-speed="7000">3.000</span>
                <br /><span className="SanFranciscoDisplay-Bold">Nhân viên</span>
              </div>
            </div>
            <div className="col-lg2 pt-3 pt-sm-5 pb-5">
              <div className="icon"><span className="ntl-kho"><span className="path1"></span><span className="path2"></span><span className="path3"></span><span className="path4"></span><span className="path5"></span></span></div>
              <div className="count-tk">
                <div className="d-inline-flex">
                  <span className="timer counter-number appear" data-to="100000" data-speed="7000">100.000</span><span> m<sup>2</sup></span>
                </div>
                <br />
                <span className="SanFranciscoDisplay-Bold">Diện tích kho bãi</span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="w-100 text-center">
        <iframe width="1120" height="630" src="https://www.youtube.com/embed/WEC92P-B-Rs" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen=""></iframe>
      </div>
      <div className="w-100 wp-kh">
        <div className="container">
          <div className="w-100 text-center position-relative font-size-24 text-dark text-kh">
            <h2 className="position-relative d-inline-block pt-5 pb-0 pb-sm-5 font-size-24 "><b className="SanFranciscoDisplay-Bold">Khách hàng</b> của Nhất Tín</h2>
          </div>
        </div>
      </div>
      <div className="w-100 ourservice pb-2 mt-n2" id="ourservice">
        <div className="container">
          <div className="w-100 slick-initialized slick-slider" id="owlcarousel">
            <div className="slick-list draggable"><div className="slick-track" style={{ opacity: 1, width: 1170 }} ><div className="carousel-item-ykien m-2 text-center bg-FCD804 text-dark slick-slide slick-current slick-active" style={{ border: 'none', width: 374 }} data-slick-index="0" aria-hidden="false" tabIndex="0">
              <Image
                alt="Next.js logo"
                className='lazyload d-inline-block'
                src="https://ntlogistics.vn/tin-tuc/wp-content/uploads/2020/01/Ellipse-17-3.png"
                width={250}
                height={250}
              />

              <div className="carousel-caption-ykien pt-2 pl-3 pr-3 pb-4">
                <div className="text-capitalize font-size-18 text-dark font-IntelBold" style={{ minheight: 31 }}>
                  Ông Nguyễn Hữu Trọng
                </div>
                <div className="text-justify font-size-16 text-dark mt-2 summary_bottom">
                  <h4 className="text-center"><strong>Quản lý chuỗi cung ứng</strong></h4>

                  <p>Chúng tôi tin tưởng và lựa chọn sử dụng dịch vụ của Nhất Tín Logistics bởi quy mô về mạng lưới giao nhận hàng hóa phủ rộng khắp cả nước; cùng với đó là hệ thống quản trị phát triển, kết nối tốt với khách hàng. Đặc biệt, chúng tôi đánh giá cao sự uy tín về thời gian toàn trình cam kết, an toàn hàng hóa và tốc độ phản hồi cho khách hàng, đáp ứng được yêu cầu của Digiworld và vượt trội so với những đơn vị khác.  </p>
                </div>
              </div>
            </div><div className="carousel-item-ykien m-2 text-center bg-FCD804 text-dark slick-slide slick-active" style={{ border: 'none', width: 374 }} data-slick-index="1" aria-hidden="false" tabIndex="0">
                <Image
                  alt="Next.js logo"
                  className='lazyload d-inline-block'
                  src="https://ntlogistics.vn/tin-tuc/wp-content/uploads/2020/01/Ellipse-16-2.png"
                  width={250}
                  height={250}
                />

                <div className="carousel-caption-ykien pt-2 pl-3 pr-3 pb-4">
                  <div className="text-capitalize font-size-18 text-dark font-IntelBold" style={{ minheight: 31 }}>
                    Ông Trần Tấn Lộc
                  </div>
                  <div className="text-justify font-size-16 text-dark mt-2 summary_bottom">
                    <h4 className="text-center"><strong>Quản lý chuỗi cung ứng - Khu vực phía Nam</strong></h4>

                    <p>Nhất Tín Logistics đã mang lại lợi ích cho công ty chúng tôi với sự kết nối vận chuyển hàng hóa nhanh nhất đến các shop trong và ngoài tỉnh, thành phố, phục vụ bán hàng ngày càng hiệu quả. Việc chọn Nhất Tín là đối tác đồng hành đã giúp chúng tôi giảm thiểu chi phí chuyển phát nhờ lợi ích của việc chuyên môn hóa và chia sẻ hạ tầng.</p>

                    <p></p></div>
                </div>
              </div><div className="carousel-item-ykien m-2 text-center bg-FCD804 text-dark slick-slide slick-active" style={{ border: 'none', width: 374 }} data-slick-index="2" aria-hidden="false" tabIndex="0">
                <Image
                  alt="Next.js logo"
                  className='lazyload d-inline-block'
                  src="https://ntlogistics.vn/tin-tuc/wp-content/uploads/2020/01/Ellipse-18-1.png"
                  width={250}
                  height={250}
                />

                <div className="carousel-caption-ykien pt-2 pl-3 pr-3 pb-4">
                  <div className="text-capitalize font-size-18 text-dark font-IntelBold" style={{ minheight: 31 }} >
                    Ông Lê Đình Biên
                  </div>
                  <div className="text-justify font-size-16 text-dark mt-2 summary_bottom">
                    <h4 className="text-center"><strong>Trưởng kho miền Nam</strong></h4>

                    <p>Nhất Tín Logistics cung cấp cho chúng tôi dịch vụ chuyển phát nhanh tốt nhất với khả năng phục vụ tất cả các loại hình logistics trên toàn quốc. Quản lý và nhân viên và quản lý niềm nở, chăm sóc khách hàng chu đáo, quy trình được quy chuẩn, đảm bảo về thời gian cam kết. Chính vì vậy chúng tôi đã tin tưởng và lựa chọn Nhất Tín Logistics nhiều năm nay. </p>

                    <p></p>
                  </div>
                </div>
              </div></div></div>


          </div>
        </div>
      </div>
    </>

  )
}
